apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trillian_log_signer-deployment
spec:
  replicas: 3
  template:
    metadata:
      lables:
        app: trillian_log_signer
    spec:
      containers:
        - name: trillian_log_signer
          image: andygabby/trillian_log_signer:latest
          ports:
          - containerPort: 8091
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: trillian-credentials
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trillian-credentials
              key: db-password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: trillian-credentials
              key: db-name
        - name: DB_HOST
          value: mysql
